# Generated by Django 5.2.9 on 2025-12-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_hashed_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_contribution_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='avg_daily_contributions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_contribution_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_revoked_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
