# Generated by Django 5.2.9 on 2025-12-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_title_c91890_idx',
            old_name='catalog_pro_title_a3e498_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_status_521020_idx',
            old_name='catalog_pro_status_b6e3a5_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_product_9ecdd3_idx',
            old_name='catalog_pro_product_6e6e4e_idx',
        ),
    ]
