# Generated by Django 5.2.9 on 2025-12-15 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catalog_pro_title_a3e498_idx_catalog_pro_title_c91890_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('new_product', 'New Product'), ('edit_product', 'Edit Product'), ('new_publisher', 'New Publisher'), ('new_system', 'New Game System')], default='edit_product', max_length=20),
        ),
        migrations.AddField(
            model_name='publisher',
            name='representatives',
            field=models.ManyToManyField(blank=True, help_text="Users who can directly edit this publisher's products and moderate contributions", related_name='represented_publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
