# Generated by Django 5.2.9 on 2025-12-15 17:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_publisher_representatives_and_contribution_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('want_to_run', 'Want to Run'), ('running', 'Currently Running'), ('completed', 'Completed')], default='want_to_run', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 stars: would run again rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulty', models.CharField(blank=True, choices=[('easier', 'Easier than Expected'), ('as_written', 'As Written'), ('harder', 'Harder than Expected')], max_length=20)),
                ('session_count', models.PositiveIntegerField(blank=True, null=True)),
                ('player_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_runs', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adventure run',
                'verbose_name_plural': 'adventure runs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grimoire_note_id', models.CharField(blank=True, help_text='Reference to source note in Grimoire', max_length=50)),
                ('note_type', models.CharField(choices=[('prep_tip', 'Prep Tip'), ('modification', 'Modification'), ('warning', 'Warning'), ('review', 'Review')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('spoiler_level', models.CharField(choices=[('none', 'No Spoilers'), ('minor', 'Minor Spoilers'), ('major', 'Major Spoilers'), ('endgame', 'Endgame Spoilers')], default='none', max_length=20)),
                ('visibility', models.CharField(choices=[('anonymous', 'Anonymous'), ('public', 'Public')], default='public', max_length=20)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_count', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by moderator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='catalog.adventurerun')),
            ],
            options={
                'verbose_name': 'community note',
                'verbose_name_plural': 'community notes',
                'ordering': ['-upvote_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('spoiler', 'Unmarked Spoilers'), ('offensive', 'Offensive Language'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='catalog.communitynote')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'note flag',
                'verbose_name_plural': 'note flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='catalog.communitynote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'note vote',
                'verbose_name_plural': 'note votes',
            },
        ),
        migrations.AddIndex(
            model_name='adventurerun',
            index=models.Index(fields=['product', 'status'], name='catalog_adv_product_57d2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='adventurerun',
            index=models.Index(fields=['user'], name='catalog_adv_user_id_977912_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adventurerun',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='communitynote',
            index=models.Index(fields=['adventure_run'], name='catalog_com_adventu_64af02_idx'),
        ),
        migrations.AddIndex(
            model_name='communitynote',
            index=models.Index(fields=['note_type'], name='catalog_com_note_ty_fff884_idx'),
        ),
        migrations.AddIndex(
            model_name='communitynote',
            index=models.Index(fields=['spoiler_level'], name='catalog_com_spoiler_f18faa_idx'),
        ),
        migrations.AddIndex(
            model_name='communitynote',
            index=models.Index(fields=['is_flagged'], name='catalog_com_is_flag_40eff9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='noteflag',
            unique_together={('user', 'note')},
        ),
        migrations.AlterUniqueTogether(
            name='notevote',
            unique_together={('user', 'note')},
        ),
    ]
