# Generated by Django 5.2.9 on 2025-12-16 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_community_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='author_names',
            field=models.JSONField(blank=True, default=list, help_text='Author names as strings, pending ProductCredit linking'),
        ),
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.JSONField(blank=True, default=list, help_text="Genre tags like ['horror', 'mystery']"),
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace_urls',
            field=models.JSONField(blank=True, default=list, help_text='Marketplace URLs: [{platform, url, label?}]. Max 4 entries.'),
        ),
    ]
