# Generated by Django 5.2.9 on 2025-12-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_contribution_claimed_at_contribution_claimed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesystem',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='gamesystem',
            name='website_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('sourcebook', 'Sourcebook'), ('supplement', 'Supplement'), ('bestiary', 'Bestiary'), ('tools', 'Tools'), ('magazine', 'Magazine'), ('core_rules', 'Core Rules'), ('core_rulebook', 'Core Rulebook'), ('setting', 'Setting'), ('character_options', 'Character Options'), ('gm_tools', 'GM Tools'), ('map', 'Map'), ('zine', 'Zine'), ('screen', 'GM Screen'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
